---
- name: install grub theme
  pacman:
    name:
      - grub-theme-vimix

- name: Copy vimix theme in boot partition
  copy:
    src: "/usr/share/grub/themes/{{ grub_theme }}/"
    dest: "/boot/grub/themes/{{ grub_theme }}/"
    remote_src: yes

- name: Set grub configuration
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_THEME='
    line: 'GRUB_THEME="/boot/grub/themes/{{ grub_theme }}/theme.txt"'

- name: Change grub wallpaper and theme
  copy:
    src: "grub/{{ item }}"
    dest: "/boot/grub/themes/{{ grub_theme }}/{{ item }}"
  with_items:
    - background.jpeg
    - theme.txt

- name: Reload grub configuration
  shell: grub-mkconfig -o /boot/grub/grub.cfg
  changed_when: false
