---
- name: install audio tools
  pacman:
    name:
      - alsa-firmware
      - alsa-utils
      #- paprefs
      - pavucontrol
      - pulseaudio
      - pulseaudio-alsa
  become: true

- name: configure x11 key bindings
  copy:
    src: xbindkeysrc
    dest: /home/{{ user.name }}/.xbindkeysrc
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  become: true
  become_user: "{{ user.name }}"
