---
- name: Enable sudo access for wheel group
  replace:
    path: /etc/sudoers
    regexp: '^#\s*%wheel\s+ALL=\(.*\)\s+ALL'
    replace: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: Enable sudo no passwd
  replace:
    path: /etc/sudoers
    regexp: '%wheel\s+ALL=\(ALL\)\s+ALL'
    replace: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: Ensure group "{{ item }}" exists
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ user.groups }}"

- name: Ensure group "{{ user.name }}" exists
  group:
    name: "{{ user.name }}"
    state: present

- name: create normal user
  user:
    name: "{{ user.name }}"
    group: "{{ user.name }}"
    password: "{{ 'toor' | password_hash('sha512') }}"
    update_password: on_create
    create_home: true
    groups: "{{ user.groups }}"
  become: true
