---
- name: Enable sudo access for wheel group
  replace:
    path: /etc/sudoers
    regexp: '^#\s*%wheel\s+ALL=\(.*\)\s+ALL'
    replace: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: Enable sudo no passwd
  replace:
    path: /etc/sudoers
    regexp: '%wheel\s+ALL=\(ALL\)\s+ALL'
    replace: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: Ensure group "{{ item }}" exists
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ user.groups }}"

- name: Ensure group "{{ user.name }}" exists
  group:
    name: "{{ user.name }}"
    state: present

- name: Create hashed password
  become: true
  ansible.builtin.command: "openssl passwd -6 {{ user.password }}"
  register: hashed_password
  no_log: true

- name: create normal user
  user:
    name: "{{ user.name }}"
    group: "{{ user.name }}"
    password: "{{ hashed_password.stdout }}"
    update_password: on_create
    create_home: true
    groups: "{{ user.groups }}"
  become: true
